### ISSUE TITLE
Error found at A2 demo

### ISSUE THREAD

**Issue by asangphukieo** [domdfcoding/PyMassSpec#1]
I try to test the scripts in 'pyms-demo/A2'
I found many issues e.g.
   - path to the many methods not correct e.g.  pyms.GCMS.Function import build_intensity_matrix_i 
 >>> pyms.IntensityMatrix import build_intensity_matrix_i

   - get_tic() method line 85 >>> unsupported as of 2.2.0. Use :attr:`pyms.GCMS.Class.tic` instead
      - when use tic() >>> TypeError: 'IonChromatogram' object is not callable

 PS: I test with MM-10.0_1_no_processing.cdf

Thank you

**Comment by domdfcoding** [comment]
Thanks for bringing this to my attention. A lot of the demos didn't get updated when I refactored the code. I'm currently in the process of updating them.
